name: ci
on:
  push:
    branches: [main, next]
  pull_request:
    branches: ['*']

jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-node@v4
        with:
          bun-version: 20.x
      - run: npm install
      - run: npm run test
      - run: npm run test:e2e
